/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 31 14:38:21 GMT 2026
 */

package org.apache.bookkeeper.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.codahale.metrics.InstrumentedThreadFactory;
import com.codahale.metrics.MetricRegistry;
import com.google.common.collect.ImmutableSet;
import com.google.common.collect.ImmutableSortedSet;
import io.netty.util.HashedWheelTimer;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.SortedSet;
import java.util.Stack;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.Vector;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.TimeUnit;
import org.apache.bookkeeper.client.BookieAddressResolverDisabled;
import org.apache.bookkeeper.client.BookiesHealthInfo;
import org.apache.bookkeeper.client.DistributionSchedule;
import org.apache.bookkeeper.client.EnsemblePlacementPolicy;
import org.apache.bookkeeper.client.ITopologyAwareEnsemblePlacementPolicy;
import org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicy;
import org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy;
import org.apache.bookkeeper.net.BookieId;
import org.apache.bookkeeper.net.BookieNode;
import org.apache.bookkeeper.net.DNSToSwitchMapping;
import org.apache.bookkeeper.net.Node;
import org.apache.bookkeeper.net.ScriptBasedMapping;
import org.apache.bookkeeper.proto.BookieAddressResolver;
import org.apache.bookkeeper.stats.CachingStatsLogger;
import org.apache.bookkeeper.stats.NullStatsLogger;
import org.apache.bookkeeper.stats.StatsLogger;
import org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider;
import org.eclipse.jetty.util.InetAddressSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.lang.MockThread;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class RackawareEnsemblePlacementPolicy_ESTest extends RackawareEnsemblePlacementPolicy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy();
      ArrayDeque<BookieNode> arrayDeque0 = new ArrayDeque<BookieNode>();
      ImmutableSet<Node> immutableSet0 = ImmutableSet.copyOf((Iterable<? extends Node>) arrayDeque0);
      InetAddressSet inetAddressSet0 = new InetAddressSet();
      TopologyAwareEnsemblePlacementPolicy.RRTopologyAwareCoverageEnsemble topologyAwareEnsemblePlacementPolicy_RRTopologyAwareCoverageEnsemble0 = new TopologyAwareEnsemblePlacementPolicy.RRTopologyAwareCoverageEnsemble(2636, 2, 2636, 500, inetAddressSet0, 877, (byte)82);
      // Undeclared exception!
      try { 
        rackawareEnsemblePlacementPolicy0.selectFromNetworkLocation("K}?4bnwL*O![wrG9E", (Set<Node>) immutableSet0, (ITopologyAwareEnsemblePlacementPolicy.Predicate<BookieNode>) topologyAwareEnsemblePlacementPolicy_RRTopologyAwareCoverageEnsemble0, (ITopologyAwareEnsemblePlacementPolicy.Ensemble<BookieNode>) topologyAwareEnsemblePlacementPolicy_RRTopologyAwareCoverageEnsemble0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Network Location path does not start with /: K}?4bnwL*O![wrG9E
         //
         verifyException("org.apache.bookkeeper.net.NodeBase", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy();
      BookieId bookieId0 = BookieId.parse("reppDnsResolverClass");
      BookieId[] bookieIdArray0 = new BookieId[3];
      bookieIdArray0[0] = bookieId0;
      bookieIdArray0[1] = bookieId0;
      bookieIdArray0[2] = bookieId0;
      ImmutableSet<BookieId> immutableSet0 = ImmutableSet.of(bookieId0, bookieId0, bookieId0, bookieId0, bookieId0, bookieId0, bookieIdArray0);
      String[] stringArray0 = new String[3];
      stringArray0[0] = "reppDnsResolverClass";
      stringArray0[1] = "reppDnsResolverClass";
      stringArray0[2] = "ensembleRandomReadReordering";
      ImmutableSet<String> immutableSet1 = ImmutableSet.copyOf(stringArray0);
      TopologyAwareEnsemblePlacementPolicy.RRTopologyAwareCoverageEnsemble topologyAwareEnsemblePlacementPolicy_RRTopologyAwareCoverageEnsemble0 = new TopologyAwareEnsemblePlacementPolicy.RRTopologyAwareCoverageEnsemble(2088, (-772), 46, (-1298), immutableSet1, 0, 0);
      TopologyAwareEnsemblePlacementPolicy.TruePredicate topologyAwareEnsemblePlacementPolicy_TruePredicate0 = TopologyAwareEnsemblePlacementPolicy.TruePredicate.INSTANCE;
      // Undeclared exception!
      try { 
        rackawareEnsemblePlacementPolicy0.newEnsemble(0, (-1412), (-1412), (Set<BookieId>) immutableSet0, (ITopologyAwareEnsemblePlacementPolicy.Ensemble<BookieNode>) topologyAwareEnsemblePlacementPolicy_RRTopologyAwareCoverageEnsemble0, (ITopologyAwareEnsemblePlacementPolicy.Predicate<BookieNode>) topologyAwareEnsemblePlacementPolicy_TruePredicate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy(false);
      TreeSet<BookieId> treeSet0 = new TreeSet<BookieId>();
      HashMap<String, byte[]> hashMap0 = new HashMap<String, byte[]>();
      TopologyAwareEnsemblePlacementPolicy.EnsembleForReplacementWithNoConstraints topologyAwareEnsemblePlacementPolicy_EnsembleForReplacementWithNoConstraints0 = TopologyAwareEnsemblePlacementPolicy.EnsembleForReplacementWithNoConstraints.INSTANCE;
      List<BookieId> list0 = topologyAwareEnsemblePlacementPolicy_EnsembleForReplacementWithNoConstraints0.toList();
      BookieId bookieId0 = BookieId.parse("reppDnsResolverClass");
      // Undeclared exception!
      try { 
        rackawareEnsemblePlacementPolicy0.replaceBookie(0, 1, 2056, hashMap0, list0, bookieId0, treeSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy();
      TreeMap<String, byte[]> treeMap0 = new TreeMap<String, byte[]>();
      // Undeclared exception!
      try { 
        rackawareEnsemblePlacementPolicy0.newEnsemble(2487, 2487, 2487, (Map<String, byte[]>) treeMap0, (Set<BookieId>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ScriptBasedMapping scriptBasedMapping0 = new ScriptBasedMapping();
      HashedWheelTimer hashedWheelTimer0 = new HashedWheelTimer();
      PrometheusMetricsProvider prometheusMetricsProvider0 = new PrometheusMetricsProvider();
      StatsLogger statsLogger0 = prometheusMetricsProvider0.getStatsLogger("RLh75h");
      BookieAddressResolverDisabled bookieAddressResolverDisabled0 = new BookieAddressResolverDisabled();
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy(false);
      rackawareEnsemblePlacementPolicy0.initialize((DNSToSwitchMapping) scriptBasedMapping0, hashedWheelTimer0, false, 2458, 8000, false, 60, 60, false, true, false, statsLogger0, (BookieAddressResolver) bookieAddressResolverDisabled0);
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      ImmutableSet<BookieId> immutableSet0 = ImmutableSet.of();
      ImmutableSortedSet<BookieId> immutableSortedSet0 = ImmutableSortedSet.copyOf((Comparator<? super BookieId>) comparator0, (Iterable<? extends BookieId>) immutableSet0);
      ImmutableSortedSet<BookieId> immutableSortedSet1 = ImmutableSortedSet.copyOfSorted((SortedSet<BookieId>) immutableSortedSet0);
      Set<BookieId> set0 = rackawareEnsemblePlacementPolicy0.onClusterChanged(immutableSortedSet1, immutableSortedSet0);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy(false);
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      ImmutableSet<BookieId> immutableSet0 = ImmutableSet.of();
      ImmutableSortedSet<BookieId> immutableSortedSet0 = ImmutableSortedSet.copyOf((Comparator<? super BookieId>) comparator0, (Iterable<? extends BookieId>) immutableSet0);
      ImmutableSortedSet<BookieId> immutableSortedSet1 = ImmutableSortedSet.copyOfSorted((SortedSet<BookieId>) immutableSortedSet0);
      Set<BookieId> set0 = rackawareEnsemblePlacementPolicy0.onClusterChanged(immutableSortedSet1, immutableSortedSet0);
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy();
      ScriptBasedMapping scriptBasedMapping0 = new ScriptBasedMapping();
      ThreadGroup threadGroup0 = mock(ThreadGroup.class, new ViolatedAssumptionAnswer());
      MockThread mockThread0 = new MockThread(threadGroup0, "no script");
      ThreadFactory threadFactory0 = mock(ThreadFactory.class, new ViolatedAssumptionAnswer());
      doReturn(mockThread0).when(threadFactory0).newThread(any(java.lang.Runnable.class));
      MetricRegistry metricRegistry0 = new MetricRegistry();
      InstrumentedThreadFactory instrumentedThreadFactory0 = new InstrumentedThreadFactory(threadFactory0, metricRegistry0);
      TimeUnit timeUnit0 = TimeUnit.MILLISECONDS;
      HashedWheelTimer hashedWheelTimer0 = new HashedWheelTimer(instrumentedThreadFactory0, 441L, timeUnit0, 95, true);
      NullStatsLogger nullStatsLogger0 = NullStatsLogger.INSTANCE;
      BookieAddressResolverDisabled bookieAddressResolverDisabled0 = new BookieAddressResolverDisabled();
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy1 = rackawareEnsemblePlacementPolicy0.initialize((DNSToSwitchMapping) scriptBasedMapping0, hashedWheelTimer0, true, (-2029), 2, true, 95, 2, true, true, (StatsLogger) nullStatsLogger0, (BookieAddressResolver) bookieAddressResolverDisabled0);
      assertSame(rackawareEnsemblePlacementPolicy1, rackawareEnsemblePlacementPolicy0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy();
      ScriptBasedMapping scriptBasedMapping0 = new ScriptBasedMapping();
      ThreadFactory threadFactory0 = mock(ThreadFactory.class, new ViolatedAssumptionAnswer());
      doReturn((Thread) null).when(threadFactory0).newThread(any(java.lang.Runnable.class));
      MetricRegistry metricRegistry0 = new MetricRegistry();
      InstrumentedThreadFactory instrumentedThreadFactory0 = new InstrumentedThreadFactory(threadFactory0, metricRegistry0);
      TimeUnit timeUnit0 = TimeUnit.MILLISECONDS;
      HashedWheelTimer hashedWheelTimer0 = new HashedWheelTimer(instrumentedThreadFactory0, 441L, timeUnit0, 95, true);
      NullStatsLogger nullStatsLogger0 = NullStatsLogger.INSTANCE;
      BookieAddressResolverDisabled bookieAddressResolverDisabled0 = new BookieAddressResolverDisabled();
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy1 = rackawareEnsemblePlacementPolicy0.initialize((DNSToSwitchMapping) scriptBasedMapping0, hashedWheelTimer0, false, 0, 98, false, 1, (-667), false, true, (StatsLogger) nullStatsLogger0, (BookieAddressResolver) bookieAddressResolverDisabled0);
      assertEquals("/default-rack", rackawareEnsemblePlacementPolicy1.getDefaultRack());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ScriptBasedMapping scriptBasedMapping0 = new ScriptBasedMapping();
      HashedWheelTimer hashedWheelTimer0 = new HashedWheelTimer();
      PrometheusMetricsProvider prometheusMetricsProvider0 = new PrometheusMetricsProvider();
      StatsLogger statsLogger0 = prometheusMetricsProvider0.getStatsLogger("RLh75h");
      BookieAddressResolverDisabled bookieAddressResolverDisabled0 = new BookieAddressResolverDisabled();
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy(false);
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy1 = rackawareEnsemblePlacementPolicy0.initialize((DNSToSwitchMapping) scriptBasedMapping0, hashedWheelTimer0, true, 60, 60, false, 8000, 60, false, true, statsLogger0, (BookieAddressResolver) bookieAddressResolverDisabled0);
      assertSame(rackawareEnsemblePlacementPolicy0, rackawareEnsemblePlacementPolicy1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy(false);
      ScriptBasedMapping scriptBasedMapping0 = new ScriptBasedMapping();
      TimeUnit timeUnit0 = TimeUnit.MICROSECONDS;
      HashedWheelTimer hashedWheelTimer0 = new HashedWheelTimer(10000L, timeUnit0);
      NullStatsLogger nullStatsLogger0 = new NullStatsLogger();
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy1 = rackawareEnsemblePlacementPolicy0.initialize((DNSToSwitchMapping) scriptBasedMapping0, hashedWheelTimer0, true, 4104, 1, true, (-2913), 0, false, false, true, (StatsLogger) nullStatsLogger0, (BookieAddressResolver) null);
      assertSame(rackawareEnsemblePlacementPolicy0, rackawareEnsemblePlacementPolicy1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy();
      ScriptBasedMapping scriptBasedMapping0 = new ScriptBasedMapping();
      NullStatsLogger nullStatsLogger0 = new NullStatsLogger();
      BookieAddressResolverDisabled bookieAddressResolverDisabled0 = new BookieAddressResolverDisabled();
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy1 = rackawareEnsemblePlacementPolicy0.initialize((DNSToSwitchMapping) scriptBasedMapping0, (HashedWheelTimer) null, true, (-427), 0, false, (-427), (-916), false, false, true, (StatsLogger) nullStatsLogger0, (BookieAddressResolver) bookieAddressResolverDisabled0);
      assertEquals("/default-rack", rackawareEnsemblePlacementPolicy1.getDefaultRack());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy(false);
      HashMap<String, byte[]> hashMap0 = new HashMap<String, byte[]>();
      TopologyAwareEnsemblePlacementPolicy.EnsembleForReplacementWithNoConstraints topologyAwareEnsemblePlacementPolicy_EnsembleForReplacementWithNoConstraints0 = TopologyAwareEnsemblePlacementPolicy.EnsembleForReplacementWithNoConstraints.INSTANCE;
      List<BookieId> list0 = topologyAwareEnsemblePlacementPolicy_EnsembleForReplacementWithNoConstraints0.toList();
      BookieId bookieId0 = BookieId.parse("reppDnsResolverClass");
      ImmutableSet<BookieId> immutableSet0 = rackawareEnsemblePlacementPolicy0.readOnlyBookies;
      // Undeclared exception!
      try { 
        rackawareEnsemblePlacementPolicy0.replaceBookie(134, 0, (-4), hashMap0, list0, bookieId0, immutableSet0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.common.collect.ImmutableCollection", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy(false);
      HashMap<String, byte[]> hashMap0 = new HashMap<String, byte[]>();
      ImmutableSet<BookieId> immutableSet0 = ImmutableSet.of();
      EnsemblePlacementPolicy.PlacementResult<List<BookieId>> ensemblePlacementPolicy_PlacementResult0 = rackawareEnsemblePlacementPolicy0.newEnsemble(0, (-1110), 33, (Map<String, byte[]>) hashMap0, (Set<BookieId>) immutableSet0);
      assertEquals(EnsemblePlacementPolicy.PlacementPolicyAdherence.FAIL, ensemblePlacementPolicy_PlacementResult0.getAdheringToPolicy());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy();
      TreeSet<BookieId> treeSet0 = new TreeSet<BookieId>();
      ScriptBasedMapping scriptBasedMapping0 = new ScriptBasedMapping();
      ThreadFactory threadFactory0 = mock(ThreadFactory.class, new ViolatedAssumptionAnswer());
      doReturn((Thread) null).when(threadFactory0).newThread(any(java.lang.Runnable.class));
      MetricRegistry metricRegistry0 = new MetricRegistry();
      InstrumentedThreadFactory instrumentedThreadFactory0 = new InstrumentedThreadFactory(threadFactory0, metricRegistry0, "reppDnsResolverClass");
      TimeUnit timeUnit0 = TimeUnit.MICROSECONDS;
      HashedWheelTimer hashedWheelTimer0 = new HashedWheelTimer(instrumentedThreadFactory0, 383, timeUnit0);
      PrometheusMetricsProvider prometheusMetricsProvider0 = new PrometheusMetricsProvider();
      StatsLogger statsLogger0 = prometheusMetricsProvider0.getStatsLogger("no script");
      CachingStatsLogger cachingStatsLogger0 = new CachingStatsLogger(statsLogger0);
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy1 = rackawareEnsemblePlacementPolicy0.initialize((DNSToSwitchMapping) scriptBasedMapping0, hashedWheelTimer0, false, 383, 2, false, (-5), 383, false, false, false, (StatsLogger) cachingStatsLogger0, (BookieAddressResolver) null);
      ArrayList<BookieId> arrayList0 = new ArrayList<BookieId>(1);
      EnsemblePlacementPolicy.PlacementResult<List<BookieId>> ensemblePlacementPolicy_PlacementResult0 = rackawareEnsemblePlacementPolicy1.replaceToAdherePlacementPolicy((-200395387), (-2381), 8000, treeSet0, arrayList0);
      assertEquals(EnsemblePlacementPolicy.PlacementPolicyAdherence.FAIL, ensemblePlacementPolicy_PlacementResult0.getAdheringToPolicy());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy(true);
      TreeSet<BookieId> treeSet0 = new TreeSet<BookieId>();
      Vector<BookieId> vector0 = new Vector<BookieId>();
      BookieId bookieId0 = BookieId.parse("ensembleRandomReadReordering");
      vector0.addElement(bookieId0);
      EnsemblePlacementPolicy.PlacementResult<List<BookieId>> ensemblePlacementPolicy_PlacementResult0 = rackawareEnsemblePlacementPolicy0.replaceToAdherePlacementPolicy(0, 2733, 36, treeSet0, vector0);
      assertEquals(EnsemblePlacementPolicy.PlacementPolicyAdherence.MEETS_STRICT, ensemblePlacementPolicy_PlacementResult0.isAdheringToPolicy());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy();
      TreeSet<BookieId> treeSet0 = new TreeSet<BookieId>();
      ArrayList<BookieId> arrayList0 = new ArrayList<BookieId>(1);
      EnsemblePlacementPolicy.PlacementResult<List<BookieId>> ensemblePlacementPolicy_PlacementResult0 = rackawareEnsemblePlacementPolicy0.replaceToAdherePlacementPolicy((-200395387), (-2381), 8000, treeSet0, arrayList0);
      assertEquals(EnsemblePlacementPolicy.PlacementPolicyAdherence.FAIL, ensemblePlacementPolicy_PlacementResult0.isAdheringToPolicy());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy();
      ScriptBasedMapping scriptBasedMapping0 = new ScriptBasedMapping();
      ThreadFactory threadFactory0 = mock(ThreadFactory.class, new ViolatedAssumptionAnswer());
      doReturn((Thread) null).when(threadFactory0).newThread(any(java.lang.Runnable.class));
      MetricRegistry metricRegistry0 = new MetricRegistry();
      InstrumentedThreadFactory instrumentedThreadFactory0 = new InstrumentedThreadFactory(threadFactory0, metricRegistry0);
      TimeUnit timeUnit0 = TimeUnit.MILLISECONDS;
      HashedWheelTimer hashedWheelTimer0 = new HashedWheelTimer(instrumentedThreadFactory0, 441L, timeUnit0, 95, true);
      NullStatsLogger nullStatsLogger0 = NullStatsLogger.INSTANCE;
      BookieAddressResolverDisabled bookieAddressResolverDisabled0 = new BookieAddressResolverDisabled();
      rackawareEnsemblePlacementPolicy0.initialize((DNSToSwitchMapping) scriptBasedMapping0, hashedWheelTimer0, true, 1, 95, true, 98, 1, true, true, (StatsLogger) nullStatsLogger0, (BookieAddressResolver) bookieAddressResolverDisabled0);
      rackawareEnsemblePlacementPolicy0.uninitalize();
      assertEquals("/default-rack", rackawareEnsemblePlacementPolicy0.getDefaultRack());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy(false);
      rackawareEnsemblePlacementPolicy0.uninitalize();
      assertEquals("/default-rack", rackawareEnsemblePlacementPolicy0.getDefaultRack());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      RackawareEnsemblePlacementPolicy rackawareEnsemblePlacementPolicy0 = new RackawareEnsemblePlacementPolicy();
      Stack<BookieId> stack0 = new Stack<BookieId>();
      BookiesHealthInfo bookiesHealthInfo0 = mock(BookiesHealthInfo.class, new ViolatedAssumptionAnswer());
      DistributionSchedule.WriteSet distributionSchedule_WriteSet0 = mock(DistributionSchedule.WriteSet.class, new ViolatedAssumptionAnswer());
      doReturn((String) null, (String) null).when(distributionSchedule_WriteSet0).toString();
      doReturn(0, 0, 0).when(distributionSchedule_WriteSet0).size();
      DistributionSchedule.WriteSet distributionSchedule_WriteSet1 = rackawareEnsemblePlacementPolicy0.reorderReadLACSequence(stack0, bookiesHealthInfo0, distributionSchedule_WriteSet0);
      assertEquals(0, distributionSchedule_WriteSet1.size());
  }
}
