/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 31 14:56:14 GMT 2026
 */

package org.apache.bookkeeper.bookie;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import io.netty.buffer.PooledByteBufAllocator;
import io.netty.buffer.UnpooledByteBufAllocator;
import java.io.IOException;
import java.nio.channels.FileChannel;
import org.apache.bookkeeper.bookie.BufferedChannel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class BufferedChannel_ESTest extends BufferedChannel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/-H[W&(2]jni@h7~t");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1289);
      BufferedChannel bufferedChannel1 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0);
      ByteBuf byteBuf0 = bufferedChannel0.writeBuffer;
      // Undeclared exception!
      try { 
        bufferedChannel1.read(byteBuf0, 806L, 1289);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // minWritableBytes : -806 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/-H[W&(2]jni@h7~t");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1289);
      long long0 = bufferedChannel0.forceWrite(true);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/-H[W&(2]jni@h7~t");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      mockFileOutputStream0.write(1289);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 316, 0L);
      long long0 = bufferedChannel0.position();
      assertEquals(1L, long0);
      assertEquals(1L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("Quiet Time is too low for Microsoft Windows: {} < 1000 ms (defaulting to 1000 ms)");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      FileChannel fileChannel1 = fileChannel0.position(695L);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel1, 1289, 1L);
      long long0 = bufferedChannel0.forceWrite(false);
      assertEquals(695L, bufferedChannel0.getFileChannelPosition());
      assertEquals(695L, long0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/-H[W&(2]jni@h7~");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(true, true, true);
      BufferedChannel bufferedChannel0 = new BufferedChannel(unpooledByteBufAllocator0, fileChannel0, 2102, 0, (-2983L));
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("Quiet Time is too low for Microsoft Windows: {} < 1000 ms (defaulting to 1000 ms)");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1289, 1L);
      ByteBuf byteBuf0 = bufferedChannel0.writeBuffer;
      bufferedChannel0.write(byteBuf0);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
      assertEquals(0L, bufferedChannel0.position());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("f}/~1q<<SCD}Q`|");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = new BufferedChannel(unpooledByteBufAllocator0, fileChannel0, 0, 0);
      ByteBuf byteBuf0 = bufferedChannel0.writeBuffer;
      bufferedChannel0.read(byteBuf0, (long) 0, 0);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/-H[W&(2]jni@h7~t");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1289);
      ByteBuf byteBuf0 = bufferedChannel0.writeBuffer;
      // Undeclared exception!
      try { 
        bufferedChannel0.read(byteBuf0, (-2172L), 77);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Negative position: -2172
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/-H[W&(2]jni@h7~t");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1289);
      ByteBuf byteBuf0 = bufferedChannel0.writeBuffer;
      try { 
        bufferedChannel0.read(byteBuf0, 0L, 1289);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Read past EOF
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/-H[W&(2]jni@h7~t");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1289);
      bufferedChannel0.getNumOfBytesInWriteBuffer();
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("Quiet Time is too low for Microsoft Windows: {} < 1000 ms (defaulting to 1000 ms)");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1289, 1L);
      bufferedChannel0.flush();
      assertEquals(0L, bufferedChannel0.position());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/-H[W&(2]jni@h7~t");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1289);
      ByteBuf byteBuf0 = bufferedChannel0.writeBuffer;
      // Undeclared exception!
      try { 
        bufferedChannel0.read(byteBuf0, 1000000000000000L, 1289);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // srcIndex: -1530494976
         //
         verifyException("io.netty.buffer.UnsafeByteBufUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("iy#;M=\"0xJ.,+");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 485);
      ByteBuf byteBuf0 = bufferedChannel0.writeBuffer;
      bufferedChannel0.write(byteBuf0);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
      assertEquals(0L, bufferedChannel0.position());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("Quiet Time is too low for Microsoft Windows: {} < 1000 ms (defaulting to 1000 ms)");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      //  // Unstable assertion: assertEquals(0, pooledByteBufAllocator0.numThreadLocalCaches());
      
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1289, 1L);
      long long0 = bufferedChannel0.getFileChannelPosition();
      //  // Unstable assertion: assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("t/-H[W&(2]jni@h7~t");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(true);
      BufferedChannel bufferedChannel0 = new BufferedChannel(unpooledByteBufAllocator0, fileChannel0, 0, (-2042L));
      long long0 = bufferedChannel0.position();
      assertEquals(0L, long0);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }
}
